### ISSUE TITLE
The image of the vehicles with the mod shops is not visible.

### ISSUE THREAD

**Issue by xxxRetroxxx** [xyberviri/CarWanna#6]
Hello, I have a problem with the view of the vehicles in the shops mod. It only loads the view of the vehicles of a couple of them, and several of the pieces are not seen in the image. The other vehicles do not show up just when I click on view, the image is black.

![image](https://github.com/xyberviri/CarWanna/assets/151453059/60219290-95a2-471e-974f-713a6c512791)
![image](https://github.com/xyberviri/CarWanna/assets/151453059/a7273332-44ad-41c1-ba79-5c247a597564)

**Comment by xyberviri** [comment]
that second image isnt a bug, its just a side effect of how PZ renders models for cars, modded cars with parts that open/close will only show the body. 

The first image might be a issue with the vino it might be nshops, in either case you would need to reach to `Noir#4723` (im not sure if their nick has changed or not) via discord and report the issue. 

I personally do not maintain the shops mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2840330802
